#!/bin/bash

args=()
[[ -n $LOG_LEVEL        ]] && args+=(--log-level        "$LOG_LEVEL")
[[ -n $VERBOSE_INTERVAL ]] && args+=(--verbose-interval "$VERBOSE_INTERVAL")
[[ -n $HISTORY_LIMIT    ]] && args+=(--history-limit    "$HISTORY_LIMIT")

mkdir -p /home/student/.local/state/workspace-logs
mkdir -p /home/student/.config

CMD=(/xterm/xterm-rs --resource /xterm/static --port 8080)
CMD+=("${args[@]}")

if [ "$(id -u)" -eq 0 ] ; then
    NORMAL_USER="$(id -un 1001)"
    set -eu
    find "/home/${NORMAL_USER:-NO_USER_1001}" -not -user 1001 -exec chown 1001:1001 {} +
    set +eu
    exec gosu 1001:1001 "${CMD[@]}"
elif [ "$(id -u)" -eq 1001 ] ; then
    exec "${CMD[@]}"
else
    echo "ERROR:" >&2
    echo "This image can only be executed as user 1001 or as user 0 (root)." >&2
    echo "Running as user 0 will automatically step down to run as user 1001." >&2
    echo "Cannot continue as current user $(id -u); exiting." >&2
    exit 1
fi
